<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Saves user to database
     *
     * @param \stdClass $user_object
     * @return User
     */
    public function saveUser(\stdClass $user_object)
    {
        $em = $this->getEntityManager();
        //todo TwitterAdapter class
        $user = new User();
        $user->setTwitterId($user_object->id_str);
        $user->setName($user_object->name);
        $user->setScreenName($user_object->screen_name);
        $user->setLocation($user_object->location);
        $user->setDescription($user_object->description);
        $user->setUrl($user_object->url);
        $em->persist($user);
        $em->flush();

        return $user;
    }
}
